# Cloudflare Pages configuration
name = "portfoliohphcs"
compatibility_date = "2024-09-23"
pages_build_output_dir = "out"

[[kv_namespaces]]
binding = "HCHPS_DATA"
id = "37c88bf84da244cfbdad062d00ec6da8"

[ai]
binding = "AI"

[[vectorize]]
binding = "WIKI_VECTORS"
index_name = "portfolio-hchps-wiki"
